on:
  schedule:
    - cron: '0 17 * * *'     # 1:00 AM SGT
    # - cron: '45 4 * * *'     # 12:45 PM SGT
    # - cron: '30 15 * * *'    # 11:30 PM SGT
  workflow_dispatch:  # This enables manual trigger

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python api_calling.py
